// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: pkg/wimse/wit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The WITSVIDRequest message conveys parameters for requesting a WIT-SVID.
type WITSVIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The requested SPIFFE ID for the WIT-SVID. If unset, all WIT-SVIDs
	// to which the workload is entitled are requested.
	SpiffeId      string `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WITSVIDRequest) Reset() {
	*x = WITSVIDRequest{}
	mi := &file_pkg_wimse_wit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WITSVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WITSVIDRequest) ProtoMessage() {}

func (x *WITSVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wimse_wit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WITSVIDRequest.ProtoReflect.Descriptor instead.
func (*WITSVIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_wimse_wit_proto_rawDescGZIP(), []int{0}
}

func (x *WITSVIDRequest) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

// The WITSVIDResponse message carries WIT-SVIDs .
type WITSVIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	// A list of WITSVID messages, each of which includes a single WIT-SVID and
	// its private key.
	Svids         []*WITSVID `protobuf:"bytes,1,rep,name=svids,proto3" json:"svids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WITSVIDResponse) Reset() {
	*x = WITSVIDResponse{}
	mi := &file_pkg_wimse_wit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WITSVIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WITSVIDResponse) ProtoMessage() {}

func (x *WITSVIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wimse_wit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WITSVIDResponse.ProtoReflect.Descriptor instead.
func (*WITSVIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_wimse_wit_proto_rawDescGZIP(), []int{1}
}

func (x *WITSVIDResponse) GetSvids() []*WITSVID {
	if x != nil {
		return x.Svids
	}
	return nil
}

// The WITSVID message carries a single SVID and all associated information,
// including the WIT bundle for the trust domain.
type WITSVID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	// The SPIFFE ID of the SVID in this entry
	SpiffeId string `protobuf:"bytes,1,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Required.
	// Encoded WIT SVID using compact JWS serialization.
	WitSvid string `protobuf:"bytes,2,opt,name=wit_svid,json=witSvid,proto3" json:"wit_svid,omitempty"`
	// Required.
	// JWK (RFC 7517) encoded private key for the WIT SVID.
	WitSvidKey string `protobuf:"bytes,3,opt,name=wit_svid_key,json=witSvidKey,proto3" json:"wit_svid_key,omitempty"`
	// Optional.
	// An operator-specified string used to provide guidance on how this identity
	// should be used by a workload when more than one SVID is returned.
	// For example, `internal` and `external` to indicate a SVID for internal or
	// external use, respectively.
	Hint          string `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WITSVID) Reset() {
	*x = WITSVID{}
	mi := &file_pkg_wimse_wit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WITSVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WITSVID) ProtoMessage() {}

func (x *WITSVID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wimse_wit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WITSVID.ProtoReflect.Descriptor instead.
func (*WITSVID) Descriptor() ([]byte, []int) {
	return file_pkg_wimse_wit_proto_rawDescGZIP(), []int{2}
}

func (x *WITSVID) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *WITSVID) GetWitSvid() string {
	if x != nil {
		return x.WitSvid
	}
	return ""
}

func (x *WITSVID) GetWitSvidKey() string {
	if x != nil {
		return x.WitSvidKey
	}
	return ""
}

func (x *WITSVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

// The WITBundlesRequest message conveys parameters for requesting WIT
// bundles. There are currently no such parameters.
type WITBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WITBundlesRequest) Reset() {
	*x = WITBundlesRequest{}
	mi := &file_pkg_wimse_wit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WITBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WITBundlesRequest) ProtoMessage() {}

func (x *WITBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wimse_wit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WITBundlesRequest.ProtoReflect.Descriptor instead.
func (*WITBundlesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_wimse_wit_proto_rawDescGZIP(), []int{3}
}

// The WITBundlesResponse message carries a map of trust bundles the workload
// should trust.
type WITBundlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	// WIT trust bundles belonging to trust domains that the workload should
	// trust, keyed by the SPIFFE ID of the trust domain.
	// Bundles are encoded in JWK set (RFC 7517) format.
	Bundles       map[string]string `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WITBundlesResponse) Reset() {
	*x = WITBundlesResponse{}
	mi := &file_pkg_wimse_wit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WITBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WITBundlesResponse) ProtoMessage() {}

func (x *WITBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_wimse_wit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WITBundlesResponse.ProtoReflect.Descriptor instead.
func (*WITBundlesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_wimse_wit_proto_rawDescGZIP(), []int{4}
}

func (x *WITBundlesResponse) GetBundles() map[string]string {
	if x != nil {
		return x.Bundles
	}
	return nil
}

var File_pkg_wimse_wit_proto protoreflect.FileDescriptor

var file_pkg_wimse_wit_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x69, 0x6d, 0x73, 0x65, 0x2f, 0x77, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0e, 0x57, 0x49, 0x54, 0x53, 0x56, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x69, 0x66, 0x66,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x69, 0x66,
	0x66, 0x65, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x57, 0x49, 0x54, 0x53, 0x56, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x76, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x57, 0x49, 0x54, 0x53, 0x56, 0x49, 0x44,
	0x52, 0x05, 0x73, 0x76, 0x69, 0x64, 0x73, 0x22, 0x77, 0x0a, 0x07, 0x57, 0x49, 0x54, 0x53, 0x56,
	0x49, 0x44, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x77, 0x69, 0x74, 0x5f, 0x73, 0x76, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x77, 0x69, 0x74, 0x53, 0x76, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x77, 0x69,
	0x74, 0x5f, 0x73, 0x76, 0x69, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x77, 0x69, 0x74, 0x53, 0x76, 0x69, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74,
	0x22, 0x13, 0x0a, 0x11, 0x57, 0x49, 0x54, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x57, 0x49, 0x54, 0x42, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07,
	0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x57, 0x49, 0x54, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0x48, 0x0a, 0x14, 0x4d, 0x69, 0x6e, 0x69, 0x53, 0x50, 0x49, 0x52,
	0x45, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x50, 0x49, 0x12, 0x30, 0x0a, 0x0b,
	0x4d, 0x69, 0x6e, 0x74, 0x57, 0x49, 0x54, 0x53, 0x56, 0x49, 0x44, 0x12, 0x0f, 0x2e, 0x57, 0x49,
	0x54, 0x53, 0x56, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x57,
	0x49, 0x54, 0x53, 0x56, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x66,
	0x69, 0x64, 0x65, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x77, 0x69,
	0x6d, 0x73, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_wimse_wit_proto_rawDescOnce sync.Once
	file_pkg_wimse_wit_proto_rawDescData []byte
)

func file_pkg_wimse_wit_proto_rawDescGZIP() []byte {
	file_pkg_wimse_wit_proto_rawDescOnce.Do(func() {
		file_pkg_wimse_wit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_wimse_wit_proto_rawDesc), len(file_pkg_wimse_wit_proto_rawDesc)))
	})
	return file_pkg_wimse_wit_proto_rawDescData
}

var file_pkg_wimse_wit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_wimse_wit_proto_goTypes = []any{
	(*WITSVIDRequest)(nil),     // 0: WITSVIDRequest
	(*WITSVIDResponse)(nil),    // 1: WITSVIDResponse
	(*WITSVID)(nil),            // 2: WITSVID
	(*WITBundlesRequest)(nil),  // 3: WITBundlesRequest
	(*WITBundlesResponse)(nil), // 4: WITBundlesResponse
	nil,                        // 5: WITBundlesResponse.BundlesEntry
}
var file_pkg_wimse_wit_proto_depIdxs = []int32{
	2, // 0: WITSVIDResponse.svids:type_name -> WITSVID
	5, // 1: WITBundlesResponse.bundles:type_name -> WITBundlesResponse.BundlesEntry
	0, // 2: MiniSPIREWorkloadAPI.MintWITSVID:input_type -> WITSVIDRequest
	1, // 3: MiniSPIREWorkloadAPI.MintWITSVID:output_type -> WITSVIDResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_wimse_wit_proto_init() }
func file_pkg_wimse_wit_proto_init() {
	if File_pkg_wimse_wit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_wimse_wit_proto_rawDesc), len(file_pkg_wimse_wit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_wimse_wit_proto_goTypes,
		DependencyIndexes: file_pkg_wimse_wit_proto_depIdxs,
		MessageInfos:      file_pkg_wimse_wit_proto_msgTypes,
	}.Build()
	File_pkg_wimse_wit_proto = out.File
	file_pkg_wimse_wit_proto_goTypes = nil
	file_pkg_wimse_wit_proto_depIdxs = nil
}
