// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/wimse/wit.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniSPIREWorkloadAPI_MintWITSVID_FullMethodName = "/MiniSPIREWorkloadAPI/MintWITSVID"
)

// MiniSPIREWorkloadAPIClient is the client API for MiniSPIREWorkloadAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiniSPIREWorkloadAPIClient interface {
	MintWITSVID(ctx context.Context, in *WITSVIDRequest, opts ...grpc.CallOption) (*WITSVIDResponse, error)
}

type miniSPIREWorkloadAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniSPIREWorkloadAPIClient(cc grpc.ClientConnInterface) MiniSPIREWorkloadAPIClient {
	return &miniSPIREWorkloadAPIClient{cc}
}

func (c *miniSPIREWorkloadAPIClient) MintWITSVID(ctx context.Context, in *WITSVIDRequest, opts ...grpc.CallOption) (*WITSVIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WITSVIDResponse)
	err := c.cc.Invoke(ctx, MiniSPIREWorkloadAPI_MintWITSVID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniSPIREWorkloadAPIServer is the server API for MiniSPIREWorkloadAPI service.
// All implementations should embed UnimplementedMiniSPIREWorkloadAPIServer
// for forward compatibility.
type MiniSPIREWorkloadAPIServer interface {
	MintWITSVID(context.Context, *WITSVIDRequest) (*WITSVIDResponse, error)
}

// UnimplementedMiniSPIREWorkloadAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniSPIREWorkloadAPIServer struct{}

func (UnimplementedMiniSPIREWorkloadAPIServer) MintWITSVID(context.Context, *WITSVIDRequest) (*WITSVIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintWITSVID not implemented")
}
func (UnimplementedMiniSPIREWorkloadAPIServer) testEmbeddedByValue() {}

// UnsafeMiniSPIREWorkloadAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniSPIREWorkloadAPIServer will
// result in compilation errors.
type UnsafeMiniSPIREWorkloadAPIServer interface {
	mustEmbedUnimplementedMiniSPIREWorkloadAPIServer()
}

func RegisterMiniSPIREWorkloadAPIServer(s grpc.ServiceRegistrar, srv MiniSPIREWorkloadAPIServer) {
	// If the following call pancis, it indicates UnimplementedMiniSPIREWorkloadAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniSPIREWorkloadAPI_ServiceDesc, srv)
}

func _MiniSPIREWorkloadAPI_MintWITSVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WITSVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniSPIREWorkloadAPIServer).MintWITSVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniSPIREWorkloadAPI_MintWITSVID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniSPIREWorkloadAPIServer).MintWITSVID(ctx, req.(*WITSVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MiniSPIREWorkloadAPI_ServiceDesc is the grpc.ServiceDesc for MiniSPIREWorkloadAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniSPIREWorkloadAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MiniSPIREWorkloadAPI",
	HandlerType: (*MiniSPIREWorkloadAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintWITSVID",
			Handler:    _MiniSPIREWorkloadAPI_MintWITSVID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/wimse/wit.proto",
}
